package Commands;

public enum Command {
    UPLOAD,
    UPLOAD_AND_DELETE,
    DOWNLOAD,
    DOWNLOAD_AND_DELETE,
    RENAME_FILE,
    DELETE_FILE,
    CREATE_DIRECTORY,
    DELETE_DIRECTORY,
    RENAME_DIRECTORY,
    UP_CATALOG,
    DOWN_CATALOG;
}
